### ISSUE TITLE
Could not find package spatie/mailcoach ...

### ISSUE THREAD

**Issue by lostdesign** [spatie/Mailcoach#15]
I was running `composer create-project spatie/Mailcoach` and got the following issue:

```Could not find package spatie/mailcoach with stability stable in a version installable using your PHP version 7.3.11.```

Any hints?

**Comment by freekmurze** [comment]
Mailcoach requires PHP 7.4

**Comment by lostdesign** [comment]
Oh... The `Package Docs` reference requirements and it says it there. Perhaps it could help to also link the requirements on the `App Docs`?

**Comment by freekmurze** [comment]
Thanks for the suggestion. I'll mention it there too.
