### ISSUE TITLE
Horizontal scrollbars are showing when using Unlayer

### ISSUE THREAD

**Issue by freekmurze** [spatie/Mailcoach#18]
<img width="640" alt="Screenshot 2020-03-10 at 16 51 10" src="https://user-images.githubusercontent.com/483853/76332237-671f5080-62f0-11ea-814f-59125556721e.png">

**Comment by riasvdv** [comment]
This is happening inside the Unlayer iframe, there's not really antything we can do about it

It only seems to be happening inside the HTML block though, which is rarely needed
