### ISSUE TITLE
Database storage for app configuration

### ISSUE THREAD

**Issue by dwightwatson** [spatie/Mailcoach#26]
I've deployed Mailcoach on Heroku because it was a low maintenance option. However I noticed that the configuration settings kept being removed. After doing some digging it looks like it's because Mailcoach persists settings (like mail settings, or the editor preferences) to files on the disk. Unfortunately in Heroku the disk isn't exactly persistent - it's replaced upon deployment, or every 24 hours.

Is there an alternative to use the database (or Redis) for app configuration, so that it remains even when the web instance is destroyed? Or will I need to host Mailcoach on a regular server?

**Comment by freekmurze** [comment]
Right now, we are going to leave it as it, so you'll have to use a regular server. In the next major version we'll consider moving all config to the db.
