### ISSUE TITLE
HtmlRule doesn't pass with multiple query string parameters

### ISSUE THREAD

**Issue by ChrisSFR** [spatie/Mailcoach#27]
It's a duplicate of this one here, but since it's more a bug for me than a question, I repost it here.

https://github.com/spatie/mailcoach-support/issues/123

We have problems to add href links with multiple query string parameters.

Steps to reproduce:
Edit the email content of a campaign with the editor of your choice. (In our case monaco or Unlayer)

Add a link to a text or button with multiple Query String parameters:

`<a href="https://example.com?foo=bar&bar=foo">Test</a>`

And hit Save Content.

It will throw a The HTML is not valid (DOMDocument::loadHTML(): htmlParseEntityRef: expecting ';' in Entity, line: 1).

When using only one query param it works
`<a href="https://example.com?foo=bar">Test</a>`

I think the HtmlRule isn't passing. But I don't know why yet.

When we edit the template itself, it works.

**Comment by jab1000** [comment]
Hi Chris, I just had this issue too -- in the link URL it needs to "&amp;" instead.   <a href="https://example.com?foo=bar&amp;bar=foo">Test</a>

**Comment by freekmurze** [comment]
@ChrisSFR does @jab1000 's suggestion solve this for you? If not, I'd be willing to add a setting that disable the `HtmlRule`.

**Comment by ChrisSFR** [comment]
@jab1000 thanks for your hint. 
@freekmurze I will go for the &amp; solution for now. But it seems a little bit laborious for me. 
I like the HtmlRule so far :D Maybe there is an auto encoding option in Unlayer.
