### ISSUE TITLE
CSV Import timing out....

### ISSUE THREAD

**Issue by jab1000** [spatie/Mailcoach#28]
I got everything fully setup (standalone setup) and sent out a few tests emails.... decided time to bring in our subscribers which are 2 different CSV files and both about 100k emails.   First upload try it imported about 3,883 on both of the 2 different imports before horizon reporting it as "timing out".    I tried changing PHP's (php.ini) file timeout to be 0 (no timeout) and unfortunately that did not work either.... same timeout issue.

```
Illuminate\Queue\MaxAttemptsExceededException: Spatie\Mailcoach\Jobs\ImportSubscribersJob has been attempted too many times or run too long. The job may have previously timed out. in /var/www/mailcoach/vendor/laravel/framework/src/Illuminate/Queue/Worker.php:647
```

How much smaller to do I have to divide things up to get our emails loaded up?   REALLY hoping I can import in "larger chunks" since if I have to do it as 3500 at time that would never work.

**Comment by jab1000** [comment]
I tried 1,000 in a CSV and it worked perfectly.... I then tried 10,000 entries and it "seemed to crash" since another "failed job" incremented with the same message as above unfortunately.

Thoughts on getting these imported?

**Comment by jab1000** [comment]
Figured I should probably add.... zero "errors" in the storage/logs file either.

**Comment by jab1000** [comment]
I did update "config/horizon" supervisor and added a "timeout=>900" to it:
```
'supervisor-1' => [
                'connection' => 'redis',
                'queue' => ['default'],
                'balance' => 'simple',
                'processes' => 10,
                'tries' => 2,
                'timeout' => 900,
            ]
```

I was able to import in the 10,000 CSV file then without issues.   Testing now on the BIG file of about 120k now and it seems to be importing.... count is increasing but out of here for now while it "works".

**Comment by freekmurze** [comment]
I've updated our docs so that a higher timeout value is suggested by default.
