### ISSUE TITLE
Throttling... turn off?

### ISSUE THREAD

**Issue by jab1000** [spatie/Mailcoach#29]
We use Amazon SES and have in the past been using "Sendy" and wanted to switch over fully to MailCoach.   Our normally "marketing email" is about 180k emails sent out at a single time via Amazon SES.  Yes, our "email permissions" in Amazon are 1M send per 24/hours with a rate of 90/second.  

Wanting to know if we should turn off "throttling" since I read in there (config/mailcoach.php) that it is set to only do 10/second at a time?   We would like to crank that up to about 50ish/second instead -- should we just tweak it there?   How does this compare to the "setting" for SES when setting up mailcoach?

Thanks!

**Comment by freekmurze** [comment]
If you want to turn off throttling completely, you can set the `throttling.enabled` key in the `laravel-mailcoach` config file to `false`.

However, we recommend leaving this turned on, and set the value of  `throttling.allowed_number_jobs_in_timespan` to a slightly lower value than your SES account allows. This will allow for transactional mails (like the confirmation and welcome mails) to be sent, even if you are sending out a campaign.
