### ISSUE TITLE
Action Spatie\MailcoachSesFeedback\SesWebhookController not defined

### ISSUE THREAD

**Issue by danjdewhurst** [spatie/Mailcoach#32]
Hi,

Fresh install of Mailcoach, PHP 7.4. Everything works fine until `php artisan optimize` is ran. I then get the following when visiting `/settings/mail-configuration`:

`[2020-04-06 16:24:40] production.ERROR: Action Spatie\MailcoachSesFeedback\SesWebhookController not defined. (View: /home/xxx/repository/resources/views/app/settings/mailConfiguration/partials/ses.blade.php) {"userId":1,"exception":"[object] (Facade\\Ignition\\Exceptions\\ViewException(code: 0): Action Spatie\\MailcoachSesFeedback\\SesWebhookController not defined. (View: /home/xxx/repository/resources/views/app/settings/mailConfiguration/partials/ses.blade.php) at /home/xxx/repository/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php:459)
[stacktrace]
#0 /home/xxx/repository/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(101): Illuminate\\Routing\\UrlGenerator->action()
#1 /home/xxx/repository/resources/views/app/settings/mailConfiguration/partials/ses.blade.php(10): action()
#2 /home/xxx/repository/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(41): include('/home/ploi/reck...')
#3 /home/xxx/repository/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(57): Illuminate\\View\\Engines\\PhpEngine->evaluatePath()
#4 /home/xxx/repository/vendor/facade/ignition/src/Views/Engines/CompilerEngine.php(37): Illuminate\\View\\Engines\\CompilerEngine->get()
#5 /home/xxx/repository/vendor/laravel/framework/src/Illuminate/View/View.php(139): Facade\\Ignition\\Views\\Engines\\CompilerEngine->get()
#6 /home/xxx/repository/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\\View\\View->getContents()
#7 /home/xxx/repository/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()
#8 /home/xxx/repository/resources/views/app/settings/mailConfiguration/edit.blade.php(40): Illuminate\\View\\View->render()
#9 /home/xxx/repository/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(41): include('/home/ploi/reck...')
#10 /home/xxx/repository/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(57): Illuminate\\View\\Engines\\PhpEngine->evaluatePath()
#11 /home/xxx/repository/vendor/facade/ignition/src/Views/Engines/CompilerEngine.php(37): Illuminate\\View\\Engines\\CompilerEngine->get()
#12 /home/xxx/repository/vendor/laravel/framework/src/Illuminate/View/View.php(139): Facade\\Ignition\\Views\\Engines\\CompilerEngine->get()
#13 /home/xxx/repository/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\\View\\View->getContents()
#14 /home/xxx/repository/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()
#15 /home/xxx/repository/vendor/laravel/framework/src/Illuminate/Http/Response.php(62): Illuminate\\View\\View->render()
#16 /home/xxx/repository/vendor/laravel/framework/src/Illuminate/Http/Response.php(34): Illuminate\\Http\\Response->setContent()
#17 /home/xxx/repository/vendor/laravel/framework/src/Illuminate/Routing/Router.php(753): Illuminate\\Http\\Response->__construct()
#18 /home/xxx/repository/vendor/laravel/framework/src/Illuminate/Routing/Router.php(725): Illuminate\\Routing\\Router::toResponse()
#19 /home/xxx/repository/vendor/laravel/framework/src/Illuminate/Routing/Router.php(685): Illuminate\\Routing\\Router->prepareResponse()
#20 /home/xxx/repository/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#21 /home/xxx/repository/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#22 /home/xxx/repository/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#23 /home/xxx/repository/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(44): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#24 /home/xxx/repository/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Auth\\Middleware\\Authenticate->handle()
#25 /home/xxx/repository/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 /home/xxx/repository/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#27 /home/xxx/repository/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#28 /home/xxx/repository/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()
#29 /home/xxx/repository/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#30 /home/xxx/repository/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#31 /home/xxx/repository/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#32 /home/xxx/repository/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#33 /home/xxx/repository/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#34 /home/xxx/repository/vendor/laravel/framework/src/Illuminate/Routing/Router.php(687): Illuminate\\Pipeline\\Pipeline->then()
#35 /home/xxx/repository/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\\Routing\\Router->runRouteWithinStack()
#36 /home/xxx/repository/vendor/laravel/framework/src/Illuminate/Routing/Router.php(628): Illuminate\\Routing\\Router->runRoute()
#37 /home/xxx/repository/vendor/laravel/framework/src/Illuminate/Routing/Router.php(617): Illuminate\\Routing\\Router->dispatchToRoute()
#38 /home/xxx/repository/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Routing\\Router->dispatch()
#39 /home/xxx/repository/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#40 /home/xxx/repository/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#41 /home/xxx/repository/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#42 /home/xxx/repository/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#43 /home/xxx/repository/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#44 /home/xxx/repository/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#45 /home/xxx/repository/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#46 /home/xxx/repository/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#47 /home/xxx/repository/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle()
#48 /home/xxx/repository/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#49 /home/xxx/repository/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()
#50 /home/xxx/repository/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#51 /home/xxx/repository/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(140): Illuminate\\Pipeline\\Pipeline->then()
#52 /home/xxx/repository/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(109): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#53 /home/xxx/repository/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle()
#54 {main}`

**Comment by riasvdv** [comment]
This could be a Laravel issue, I've created a PR there https://github.com/laravel/framework/pull/32512

If it turns out to be working as intended there, I'll add named routes to all the feedback packages and use those instead.

**Comment by riasvdv** [comment]
Laravel 7.8.0 contains the fix, can you try running `composer update` and see if that fixes your issue?
