### ISSUE TITLE
See sent campaigns

### ISSUE THREAD

**Issue by renatonascalves** [spatie/Mailcoach#34]
After sending a campaign, you get lots of data about it, but you can't view the email template that was sent. :/

**Comment by looxis-renaud** [comment]
I noticed the same, and I agree that a copy of the email, that was sent, should be there in the backend.

workaround for now: add yoruself to the list of recepients, and you'll have a copy of your newsletter in your inbox :-)

**Comment by freekmurze** [comment]
You can see the sent campaign by clicking that link in the green box.

<img width="697" alt="image" src="https://user-images.githubusercontent.com/483853/79852067-77821b00-83c6-11ea-8e13-6f7495816839.png">

**Comment by renatonascalves** [comment]
Ah, tks! I see it now.
