### ISSUE TITLE
"GROUP BY clause and contains nonaggregated column 'mailcoach.mailcoach_campaign_opens.id'"

### ISSUE THREAD

**Issue by hughgrigg** [spatie/Mailcoach#37]
Seeing this error in the logs when trying to view campaign statistics:

```
(PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'mailcoach.mailcoach_campaign_opens.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
```

None of the statistics load in the UI because of this. I can see that the statistics are coming through SNS correctly and getting recorded, but Mailcoach is unable to retrieve them from the database due to this.

Looks like it's fixable by changing the sql mode for the connection.

**Comment by hughgrigg** [comment]
A workaround for this is to set `strict` to `false` for the `mysql` database connection in Mailcoach config here:

https://github.com/spatie/Mailcoach/blob/master/config/database.php#L59

**Comment by arthurkirkosa** [comment]
`Illuminate\Database\QueryException SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'db.mailcoach_campaign_opens.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by (SQL: select count(`subscriber_id`) as aggregate from (select * from `mailcoach_campaign_opens` where `mailcoach_campaign_opens`.`campaign_id` = ? and `mailcoach_campaign_opens`.`campaign_id` is not null group by `subscriber_id`) as `aggregate_table`) `

I've started receiving the same error

**Comment by riasvdv** [comment]
Should be fixed in the latest release!
