### ISSUE TITLE
Undefined variable: name

### ISSUE THREAD

**Issue by joostvanhoof** [spatie/Mailcoach#38]
I'm a little puzzled by this exception, see below. It's a copy paste so the repetition of the view name is the error as it shows up.

Laravel: 7.11.0
PHP: 7.4
Mailcoach: 2.11.5

`Undefined variable: name (View: /Users/joost/Documents/dev/freddyfeedback/vendor/spatie/laravel-mailcoach/resources/views/app/components/modal/modal.blade.php) (View: /Users/joost/Documents/dev/freddyfeedback/vendor/spatie/laravel-mailcoach/resources/views/app/components/modal/modal.blade.php) (View: /Users/joost/Documents/dev/freddyfeedback/vendor/spatie/laravel-mailcoach/resources/views/app/components/modal/modal.blade.php)
`

It seems to occur in a cached view, the filename mentioned is `storage/framework/views/79a255e6d65a19356bfb8336e1338668a961590f.php`

Running `php artisan cache:clear` and refreshing the page brings up the same error again.

The error occurs on line 2:
```
<?php $__env->startPush('modals'); ?>
    <div class="modal-backdrop | <?php echo e(($open ?? false) ? '' : 'hidden'); ?>" data-modal="<?php echo e($name); ?>" data-modal-backdrop>
        <div class="modal-wrapper <?php if(isset($large)): ?> modal-wrapper-lg <?php endif; ?>">
            <button class="modal-close" tabindex="-1" data-modal-dismiss>
                <i class="fas fa-times"></i>
            </button>
            <div class="modal">
                <?php if(isset($title)): ?>
                    <header class="modal-header">
                        <span class="modal-title"><?php echo e($title); ?></span>
                    </header>
                <?php endif; ?>
                <div class="modal-content scrollbar">
                    <?php echo e($slot); ?>
                </div>
            </div>
        </div>
    </div>
<?php $__env->stopPush(); ?>
```

**Comment by joostvanhoof** [comment]
Did a bit more digging around. Here's some interesting additional info:

- The pages that generate this error don't use Mailcoach in any way, and other pages work fine. So at first it seemed random, but then it turned out that:
- The pages that throw the error have another (non Mailcoach) modal component that was made by me
  - It's name and location: `app/resources/views/components/modal.blade.php`
  - The way 'my' modal component is included: `<x-modal>...</x-modal>` which is... just how Mailcoach includes it! This was the aha moment, confirmed by the next two points:
- The Laravel Debugbar shows that the Mailcoach modal component is rendered
- If I rename my modal component to something else like `modal-temp` and include it as `<x-modal-temp>` the error goes away
- If I change `{{ $name }}` to `{{ $name ?? '' }}` in `mailcoach/resources/views/app/components/modal/modal.blade.php` the error is also resolved (even when the two modal components have the same name).

To be honest I'm not sure what the next step is because I don't know why exactly Laravel is including both modal components.

**Comment by freekmurze** [comment]
Right now, we have registered our components without a prefix, so like `x-modal`. In think that in a future major version of the package we should rename them with a prefix so they won't  clash with components from your app. So a name like `x-mailcoach-modal` would be better.

We can't fix this now as it could be viewed as a breaking changed. The way for you to go now would be to prefix your component with `app` our something: `x-app-model`.

We'll revisit this issue when creating a new major version.

**Comment by tnylea** [comment]
Yeah, this is kind of a bummer.

I was able to fix it by running the following inside my `AppServiceProvider`:

Adding this to the `boot()` method:

```
if(request()->is('mailcoach/*') || request()->is('mailcoach')){
    $this->bootMailcoachBladeComponents();
}
```

And then I copied the logic to boot the blade components with this function:

```
public function bootMailcoachBladeComponents(){
    Blade::component('mailcoach::app.components.form.checkboxField', 'checkbox-field');
    Blade::component('mailcoach::app.components.form.radioField', 'radio-field');
    Blade::component('mailcoach::app.components.form.formButton', 'form-button');
    Blade::component('mailcoach::app.components.form.selectField', 'select-field');
    Blade::component('mailcoach::app.components.form.tagsField', 'tags-field');
    Blade::component('mailcoach::app.components.form.textField', 'text-field');
    Blade::component('mailcoach::app.components.form.htmlField', 'html-field');
    Blade::component('mailcoach::app.components.form.dateField', 'date-field');
    Blade::component(DateTimeFieldComponent::class, 'date-time-field');

    Blade::component('mailcoach::app.components.modal.modal', 'modal');

    Blade::component('mailcoach::app.components.table.tableStatus', 'table-status');
    Blade::component(THComponent::class, 'th');

    Blade::component('mailcoach::app.components.filters.filters', 'filters');
    Blade::component(FilterComponent::class, 'filter');

    Blade::component(SearchComponent::class, 'search');
    Blade::component('mailcoach::app.components.statistic', 'statistic');
    Blade::component('mailcoach::app.components.navigationItem', 'navigation-item');
    Blade::component('mailcoach::app.components.iconLabel', 'icon-label');

    Blade::component('mailcoach::app.components.help', 'help');
    Blade::component('mailcoach::app.components.counter', 'counter');

    Blade::component(ReplacerHelpTextsComponent::class, 'replacer-help-texts');

    return $this;
}
```

You'll need to include the following namespaces as well:

```
use Spatie\Mailcoach\Components\DateTimeFieldComponent;
use Spatie\Mailcoach\Components\FilterComponent;
use Spatie\Mailcoach\Components\ReplacerHelpTextsComponent;
use Spatie\Mailcoach\Components\SearchComponent;
use Spatie\Mailcoach\Components\THComponent;
use Illuminate\Support\Facades\Blade;
``` 

Really not ideal but it's working for me now. This way the Mailcoach blade components are only loaded when it is a mailcoach page.
