### ISSUE TITLE
Specify queue for welcome emails

### ISSUE THREAD

**Issue by joostvanhoof** [spatie/Mailcoach#39]
This is a feature request. The mailcoach config file lets you specify a queue for each category of job:

```
'perform_on_queue' => [
        'calculate_statistics_job' => 'mailcoach',
        'send_campaign_job' => 'send-campaign',
        'send_mail_job' => 'send-mail', // this is only used for sending campaigns?
        'send_test_mail_job' => 'mailcoach',
        'process_feedback_job' => 'mailcoach-feedback',
        'import_subscribers_job' => 'mailcoach',
    ],
```

But this config setting does not let you specify a queue for the welcome email that will be sent after subscribing. That email will go on the queue specified in `config/queue`:

```
'mailcoach-redis' => [
            'driver' => 'redis',
            'connection' => 'default',
            'queue' => env('REDIS_QUEUE', 'default'), // welcome email uses this queue
            'retry_after' => 11 * 60,
            'block_for' => null,
        ],
```

This was a bit confusing at first because the mailcoach config suggests that you can specify the queues for _all_ types of emails sent by Mailcoach.

Maybe the mailcoach `perform_on_queue` config array can have a key added called something like `send_transactional_email` so you can specify the queue there?

**Comment by joostvanhoof** [comment]
I just changed the queue name in `config/queue`:
```
'mailcoach-redis' => [
            'queue' => 'mailcoach-other'
        ],

```
and added it in `config/horizon`:

```
'mailcoach' => [
                'queue' => ['send-campaign', 'send-mail', 'mailcoach-feedback', 'mailcoach', 'mailcoach-other'],
```

then ran `php artisan config:cache` and restarted horizon, but the welcome email is still on the `default` queue.

**Comment by joostvanhoof** [comment]
@rubenvanassche friendly ping. If there's anything you need from me please let me know.

**Comment by rubenvanassche** [comment]
Hi @joostvanhoof,

Sorry for the late response, my bad! We've added this feature 11 days age in laravel-mailcoach 2.12.0! You can now use the `send_welcome_mail_job` config value to set the welcome mail queue! More information here:https://mailcoach.app/docs/v2/package/general/installation-and-setup

Thanks for using Mailcoach!
