### ISSUE TITLE
Selecting list during create campaign already?

### ISSUE THREAD

**Issue by beberlei** [spatie/Mailcoach#41]
Defaulting to use the "first" list can easily lead to mistake when you forget to pick the right list in the following edit screen, using the "first" list as default.

I would like to pick both the template and the list in the Create Campaign dialog.

**Comment by freekmurze** [comment]
@beberlei thanks for your suggestion.

@riasvdv if this is an easy-ish change to make, let's add the list to the create campaign dialog.

**Comment by riasvdv** [comment]
This is fixed in 2.13.0 of the laravel-mailcoach package

**Comment by beberlei** [comment]
@riasvdv excellent, updated our instance and it works well. Its much better now to directly have this choice, as we have 3 totally different newsletters for Tideways RFC Watch, Newsletter and internal updates, its important to pick the right one :D
