### ISSUE TITLE
Division by zero error when sending newsletter

### ISSUE THREAD

**Issue by joostvanhoof** [spatie/Mailcoach#45]
Mailcoach version 2.20.0
Laravel 7.18.0
See Honeybadger trace:

<img width="1140" alt="Screenshot 2020-07-01 at 15 40 54" src="https://user-images.githubusercontent.com/5268113/86251353-0d4dd980-bbb2-11ea-8f95-2f1282b3da45.png">

**Comment by freekmurze** [comment]
@riasvdv I think we got another regression here 😬

**Comment by riasvdv** [comment]
Yes, taking a look now

**Comment by riasvdv** [comment]
Should be fixed in 2.20.1!
