### ISSUE TITLE
Error when connecting local project in Invoker

### ISSUE THREAD

**Issue by joostvanhoof** [spatie/Mailcoach#46]
I was just trying out [Invoker](https://invoker.dev) and got the error below. Everything works fine locally and in production so not sure if this is on the Mailcoach or Invoker side, but thought I'd share.

<img width="565" alt="Screenshot 2020-07-02 at 09 33 29" src="https://user-images.githubusercontent.com/5268113/86329956-3f5d4b00-bc47-11ea-9986-a95445a8bf8f.png">

**Comment by riasvdv** [comment]
This looks to be an error with an incorrect PHP version, Mailcoach requires PHP 7.4
