### ISSUE TITLE
Fatal error when testing transactional mail

### ISSUE THREAD

**Issue by sanderdewijs** [spatie/Mailcoach#54]
Hi Mailcoach team,

When I try to send a test mail via /settings/send-transactional-test-mail, the application throws a fatal error:
Type of App\Mail\TransactionalTestMail::$theme must not be defined (as in class Illuminate\Mail\Mailable).

I'm using MailCoach v2.23.12

**Comment by dimitribocquet** [comment]
Same here

**Comment by freekmurze** [comment]
This is fixed in the latest version.
