### ISSUE TITLE
artisan view:cache command not working anymore v3

### ISSUE THREAD

**Issue by nessor** [spatie/Mailcoach#56]
Hey guys,

I have just updated my application to Laravel 8 with Mailcoach v.3.0.3 (I followed the [upgrade guide](https://mailcoach.app/docs/v3/app/installation/upgrading)  from v2 to v3) Since then the artisan view:cache command does not work anymore. Here comes the error that no view or component could be found for text-field:

```php
   InvalidArgumentException 

  Unable to locate a class or view for component [text-field].

  at vendor/laravel/framework/src/Illuminate/View/Compilers/ComponentTagCompiler.php:274
    270▕         if ($viewFactory->exists($view = $this->guessViewName($component))) {
    271▕             return $view;
    272▕         }
    273▕ 
  ➜ 274▕         throw new InvalidArgumentException(
    275▕             "Unable to locate a class or view for component [{$component}]."
    276▕         );
    277▕     }
    278▕ 

      +2 vendor frames
  3   [internal]:0
      Illuminate\View\Compilers\ComponentTagCompiler::Illuminate\View\Compilers\{closure}()

      +7 vendor frames
  11  [internal]:0
      Illuminate\Foundation\Console\ViewCacheCommand::Illuminate\Foundation\Console\{closure}()

```

A global search on my site shows that <x-text-field ... /> is only used in the Mailcoach package.
Can you confirm the error? I would not know what I had done wrong.

**Comment by riasvdv** [comment]
Are you sure you're on the latest versions of the packages? None of the code in the latest versions still use `<x-text-field .. />`

You can try running `composer info | grep mailcoach` to see all the package versions

**Comment by riasvdv** [comment]
Closing this for now, for support and issues please refer to https://github.com/spatie/laravel-mailcoach
