### ISSUE TITLE
large amount of bounces all of a sudden

### ISSUE THREAD

**Issue by jab1000** [spatie/Mailcoach#58]
We sent out a campaign last night --  email list of about 110k users (emailed 1-2 times/week) and all of a sudden it was almost 8k bounces which equated to unsubscribes too.  Normally we get about 100-200 bounces at most with around the same number of unsubscribes too.   Really weird and a first to be candid.

All email sent out via AWS SES -- any thoughts or ideas?

Thanks!

**Comment by riasvdv** [comment]
This could be related to the Google/Gmail downtime, or any other downtime, the emails are probably all of the same service.

Mailcoach just processes what we receive from AWS, it has no influence on deliverablity
